<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RanvierTrace>false</RanvierTrace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DefaultItemExcludes>$(DefaultItemExcludes);WpfProgram.cs</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="wpf/**" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <ProjectReference Include="../../src/Ranvier.CSharp/Ranvier.CSharp.fsproj" />
    <RuntimeHostConfigurationOption Include="System.Runtime.TieredCompilation" Value="false" />
  </ItemGroup>
</Project>
