<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Ranvier</RootNamespace>
        <AssemblyName>Ranvier</AssemblyName>
        <PackageId>Ranvier</PackageId>
        <Title>Ranvier</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Library.fs" />
        <None Include="../../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
