name: workflow.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Run Script
        run: dotnet fsi build.fsx -- publish --nuget-key ${{ secrets.NUGET_KEY }}
